class Spinach::Features::SusPointersCalculation < Spinach::FeatureSteps
  step 'a set of chromosomes with positive fitness values' do
    @are_there_negative_fit = false
    @input = {}
    chromosomes = []
    fit_data =   [ 1, 15, 23, 1, 5, 7, 8 ]
    fit_data.each do |fit|
      chromo = Chromosome.new
      chromo.fitness = fit
      chromosomes << chromo
    end
    @input[:chromosomes] = chromosomes
  end

  step 'the required number of selections is 3' do
    @input[:num_required_selects] = 3
  end

  step 'the array of pointers generated by the SUS should correspond to each individual\'s fitness' do
    pointers = SUS::sample(@input[:chromosomes], @input[:num_required_selects])
    expect(pointers.size).to eq(@input[:num_required_selects])
    (1...(pointers.size - 1)).each do |i|
      expect(pointers[i - 1]).to be <= pointers[i]
    end
  end

  step 'a set of chromosomes with negative fitness values' do
    @are_there_negative_fit = true
    @input = {}
    chromosomes = []
    fit_data =     [ -1, -15, -23, -1, -5, -7, -8 ]
    fit_data.each do |fit|
      chromo = Chromosome.new
      chromo.fitness = fit
      chromosomes << chromo
    end
    @input[:chromosomes] = chromosomes
  end
end
