@feat_sus
Feature: sus pointers calculation
  As a researcher,
  in order to perform SUS selection for a set of chromosomes,
  I want the sus pointers calculation to work correctly.
  
  @sce_positive_fits
  Scenario: Set of chromosomes with only positive fitness values
    Given a set of chromosomes with positive fitness values
    And the required number of selections is 3
    Then the array of pointers generated by the SUS should correspond to each individual's fitness

  @sce_negative_fits
  Scenario: Set of chromosomes with only negative fitness values
    Given a set of chromosomes with negative fitness values
    And the required number of selections is 3
    Then the array of pointers generated by the SUS should correspond to each individual's fitness